logging:
  level:
    ROOT: INFO
spring:
  application:
    name: PublishStatistics
  jackson.serialization.write-dates-as-timestamps: false
statisticService.windowInMs: 60000
statisticService.removeExpiredStatisticsInMs: 10000